<?php

namespace Database\Seeders;

use App\Models\DocumentType;
use App\Models\Institution;
use Illuminate\Database\Seeder;

class DocumentTypeSeeder extends Seeder
{
    public function run(): void
    {
        $institution = Institution::where('slug', 'promessa')->firstOrFail();
        $id = $institution->id;

        $types = [
            // =========================================================
            // 1. JURÍDICO / INSTITUCIONAL
            // =========================================================
            [
                'name'               => 'Ata de Fundação (registrada em cartório)',
                'category'           => 'juridico',
                'sphere'             => 'interno',
                'validity_days'      => null,
                'requires_history'   => true,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\nA Ata de Fundação é lavrada no ato de constituição da associação e registrada em **Cartório de Registro de Pessoas Jurídicas**.\n\n**Passos para obter cópia autenticada:**\n1. Compareça ao cartório onde foi feito o registro original.\n2. Solicite certidão ou cópia autenticada da ata.\n3. O prazo de emissão é geralmente imediato ou em até 2 dias úteis.\n4. Custo: conforme tabela de emolumentos do TJPE.\n\n> Este documento não vence, mas editais podem exigir certidão atualizada do cartório.",
                'sort_order'         => 10,
            ],
            [
                'name'               => 'Estatuto Social Consolidado',
                'category'           => 'juridico',
                'sphere'             => 'interno',
                'validity_days'      => null,
                'requires_history'   => true,
                'is_per_person'      => false,
                'is_public_by_default' => true,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\nO Estatuto Social e suas alterações devem estar registrados em **Cartório de Registro de Pessoas Jurídicas**.\n\n**Passos:**\n1. Mantenha sempre a versão consolidada com todas as alterações aprovadas em assembleia.\n2. Cada alteração deve ser aprovada em assembleia geral e registrada em cartório.\n3. Solicite certidão de inteiro teor no cartório para editais.\n\n> Guarde o histórico de todas as versões (exigido pelo MROSC).",
                'sort_order'         => 20,
            ],
            [
                'name'               => 'Ata de Eleição e Posse da Diretoria',
                'category'           => 'juridico',
                'sphere'             => 'interno',
                'validity_days'      => null,
                'requires_history'   => true,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\nA Ata de Eleição deve ser lavrada na assembleia que elegeu a diretoria e registrada em cartório.\n\n**Passos:**\n1. Realize assembleia geral conforme previsto no estatuto.\n2. Lavrar a ata com qualificação completa de todos os eleitos.\n3. Registrar em Cartório de Registro de Pessoas Jurídicas.\n4. Publicar no Diário Oficial se exigido pelo estatuto ou por lei.\n\n> A validade é o período do mandato definido no estatuto. Cadastre a data de fim do mandato como data de vencimento.",
                'sort_order'         => 30,
            ],
            [
                'name'               => 'Outras Atas de Assembleias',
                'category'           => 'juridico',
                'sphere'             => 'interno',
                'validity_days'      => null,
                'requires_history'   => true,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\nAtas de assembleias gerais ordinárias (AGO) e extraordinárias (AGE) devem ser lavradas e assinadas pelos presentes.\n\n**Boas práticas:**\n1. Numerar e arquivar todas as atas sequencialmente.\n2. Registrar em cartório quando deliberarem sobre alterações estatutárias ou eleição de diretoria.\n3. Guardar o livro de atas ou as atas avulsas devidamente assinadas.",
                'sort_order'         => 40,
            ],
            [
                'name'               => 'Relação Nominal da Diretoria com Qualificação (MROSC)',
                'category'           => 'juridico',
                'sphere'             => 'federal',
                'validity_days'      => null,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\nDocumento produzido pela própria ONG, exigido pelo **MROSC (Lei 13.019/2014)**.\n\n**Conteúdo obrigatório:**\n- Nome completo de cada dirigente\n- RG e CPF\n- Endereço residencial\n- Cargo na diretoria\n- Período do mandato\n\n**Passos:**\n1. Elabore o documento com base na ata de eleição vigente.\n2. Assine e carimbe com o CNPJ da entidade.\n3. Atualize sempre que houver mudança na diretoria.",
                'sort_order'         => 50,
            ],
            [
                'name'               => 'Certidão de Existência Jurídica (Cartório de PJ)',
                'category'           => 'juridico',
                'sphere'             => 'interno',
                'validity_days'      => 90,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\nSolicite no **Cartório de Registro de Pessoas Jurídicas** onde a ONG está registrada.\n\n**Passos:**\n1. Compareça ao cartório com CNPJ e documento do representante legal.\n2. Solicite a \"Certidão de Inteiro Teor\" ou \"Breve Relato\".\n3. O custo segue a tabela de emolumentos do TJPE.\n4. Validade geralmente aceita pelos editais: **90 dias**.\n\n> Renove próximo ao envio de editais.",
                'sort_order'         => 60,
            ],
            [
                'name'               => 'Cartão CNPJ — Comprovante de Inscrição (RFB)',
                'category'           => 'juridico',
                'sphere'             => 'federal',
                'validity_days'      => 90,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => true,
                'official_url'       => 'https://www.gov.br/receitafederal/pt-br/assuntos/cadastros/cnpj/comprovante-de-inscricao-e-de-situacao-cadastral',
                'instructions'       => "## Como obter\n\nEmissão **gratuita e online** no portal da Receita Federal.\n\n**Passos:**\n1. Acesse: https://www.gov.br/receitafederal/pt-br/assuntos/cadastros/cnpj/comprovante-de-inscricao-e-de-situacao-cadastral\n2. Informe o CNPJ.\n3. Resolva o CAPTCHA e clique em \"Consultar\".\n4. Imprima ou salve o PDF.\n\n> Editais costumam exigir emitido há menos de **90 dias**. Emissão instantânea.",
                'sort_order'         => 70,
            ],
            [
                'name'               => 'Comprovante de Endereço da Sede',
                'category'           => 'juridico',
                'sphere'             => 'interno',
                'validity_days'      => 90,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\n**Documentos aceitos:**\n- Conta de água, luz, gás ou telefone em nome da ONG ou do responsável legal (emitida nos últimos 3 meses).\n- Contrato de locação registrado em cartório.\n- Declaração de cessão de uso do imóvel.\n\n**Dica:** Prefira documentos em nome da própria associação para evitar questionamentos.",
                'sort_order'         => 80,
            ],
            [
                'name'               => 'Alvará de Localização e Funcionamento (Prefeitura de Jaboatão)',
                'category'           => 'juridico',
                'sphere'             => 'municipal',
                'validity_days'      => 365,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => 'https://www.jaboatao.pe.gov.br',
                'instructions'       => "## Como obter\n\nSolicite na **Prefeitura de Jaboatão dos Guararapes** (Secretaria de Finanças ou Secretaria de Desenvolvimento Econômico).\n\n**Passos:**\n1. Acesse o portal da prefeitura: https://www.jaboatao.pe.gov.br\n2. Verifique se há sistema online de alvará.\n3. Caso contrário, compareça presencialmente com: CNPJ, estatuto, comprovante de endereço.\n4. O alvará normalmente é renovado **anualmente**.\n\n> ONGs podem ter tratamento diferenciado (isenção de taxas). Consulte a secretaria.",
                'sort_order'         => 90,
            ],
            [
                'name'               => 'Documentos do Responsável Legal (RG e CPF)',
                'category'           => 'juridico',
                'sphere'             => 'interno',
                'validity_days'      => null,
                'requires_history'   => false,
                'is_per_person'      => true,
                'is_public_by_default' => false,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\n**RG:** emitido pela Secretaria de Segurança Pública de PE (SSP-PE). Para segunda via, acesse: https://www.sds.pe.gov.br\n\n**CPF:** emitido pela Receita Federal ou Correios. Para impressão: https://www.gov.br/receitafederal/pt-br/assuntos/cadastros/cpf\n\n> Mantenha cópias autenticadas dos documentos do presidente e demais dirigentes.",
                'sort_order'         => 100,
            ],
            [
                'name'               => 'Declarações MROSC art. 39 (não impedimento)',
                'category'           => 'juridico',
                'sphere'             => 'federal',
                'validity_days'      => 180,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => 'https://www.gov.br/transferencias-voluntarias/pt-br',
                'instructions'       => "## Como obter\n\nAs **Declarações do art. 39 da Lei 13.019/2014 (MROSC)** são autodeclaratórias, elaboradas pela própria ONG.\n\n**Conteúdo exigido (entre outros):**\n- Não ter dirigente condenado por ato de improbidade administrativa\n- Não contratar cônjuge/parente de agente público do órgão parceiro\n- Não ter fins lucrativos\n\n**Modelos:** disponíveis no portal de transferências voluntárias: https://www.gov.br/transferencias-voluntarias/pt-br\n\n> Os modelos variam por edital. Solicite o modelo ao órgão financiador.",
                'sort_order'         => 110,
            ],

            // =========================================================
            // 2. CERTIDÕES FEDERAIS
            // =========================================================
            [
                'name'               => 'CND Federal — Certidão de Débitos Tributários Federais e Dívida Ativa da União (RFB/PGFN)',
                'category'           => 'federal',
                'sphere'             => 'federal',
                'validity_days'      => 180,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => true,
                'official_url'       => 'https://solucoes.receita.fazenda.gov.br/Servicos/certidaointernet/PJ/Emitir',
                'instructions'       => "## Como obter\n\nEmissão **gratuita e online** pela Receita Federal.\n\n**Passos:**\n1. Acesse: https://solucoes.receita.fazenda.gov.br/Servicos/certidaointernet/PJ/Emitir\n2. Informe o CNPJ.\n3. Clique em \"Emitir Certidão\".\n4. Salve o PDF (com código de autenticação).\n\n**Validade:** 180 dias.\n\n> Em caso de pendências, regularize pelo portal e-CAC: https://cav.receita.fazenda.gov.br",
                'sort_order'         => 200,
            ],
            [
                'name'               => 'CRF — Certificado de Regularidade do FGTS (Caixa Econômica Federal)',
                'category'           => 'federal',
                'sphere'             => 'federal',
                'validity_days'      => 30,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => true,
                'official_url'       => 'https://consulta-crf.caixa.gov.br',
                'instructions'       => "## Como obter\n\nEmissão **gratuita e online** pela Caixa Econômica Federal.\n\n**Passos:**\n1. Acesse: https://consulta-crf.caixa.gov.br\n2. Informe o CNPJ.\n3. O sistema gera o CRF automaticamente se estiver regular.\n4. Salve o PDF.\n\n**Validade:** 30 dias.\n\n> ONGs sem empregados ainda precisam do CRF. Em caso de irregularidade, acesse a agência da Caixa.",
                'sort_order'         => 210,
            ],
            [
                'name'               => 'CNDT — Certidão Negativa de Débitos Trabalhistas (TST)',
                'category'           => 'federal',
                'sphere'             => 'federal',
                'validity_days'      => 180,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => true,
                'official_url'       => 'https://www.tst.jus.br/certidao',
                'instructions'       => "## Como obter\n\nEmissão **gratuita e online** pelo Tribunal Superior do Trabalho (TST).\n\n**Passos:**\n1. Acesse: https://www.tst.jus.br/certidao\n2. Informe o CNPJ.\n3. Emita e salve o PDF.\n\n**Validade:** 180 dias.\n\n> Em caso de débitos trabalhistas, consulte a Vara do Trabalho responsável.",
                'sort_order'         => 220,
            ],
            [
                'name'               => 'RAIS Negativa / Recibo eSocial (anual)',
                'category'           => 'federal',
                'sphere'             => 'federal',
                'validity_days'      => 365,
                'requires_history'   => true,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => 'https://www.gov.br/esocial/pt-br',
                'instructions'       => "## Como obter\n\nA RAIS foi absorvida pelo **eSocial** (portaria MTE 1.127/2019). ONGs devem declarar anualmente.\n\n**Passos:**\n1. Acesse o eSocial: https://www.gov.br/esocial/pt-br\n2. Para entidades **sem empregados**: transmita o evento S-1000 (dados do empregador) e guarde o recibo.\n3. Editais antigos ainda podem pedir \"RAIS Negativa\" — o recibo do eSocial equivale.\n\n**Prazo:** declaração anual, geralmente até março/abril do ano seguinte.\n\n> Guarde o número de recibo de cada competência.",
                'sort_order'         => 230,
            ],
            [
                'name'               => 'Certidão de Antecedentes Criminais — Polícia Federal (dirigentes)',
                'category'           => 'federal',
                'sphere'             => 'federal',
                'validity_days'      => 180,
                'requires_history'   => false,
                'is_per_person'      => true,
                'is_public_by_default' => false,
                'official_url'       => 'https://www.gov.br/pf/pt-br/assuntos/antecedentes-criminais',
                'instructions'       => "## Como obter\n\nEmissão **gratuita e online** pela Polícia Federal.\n\n**Passos:**\n1. Acesse: https://www.gov.br/pf/pt-br/assuntos/antecedentes-criminais\n2. Faça login com Gov.br (necessário conta nível Prata ou Ouro).\n3. Selecione \"Emitir certidão de antecedentes criminais\".\n4. Salve o PDF com código de autenticação.\n\n**Validade:** 180 dias (verificar exigência do edital).\n\n> Geralmente exigida para presidente e demais dirigentes.",
                'sort_order'         => 240,
            ],
            [
                'name'               => 'Certidão CADIN/CAUC (Transferegov — convênios federais)',
                'category'           => 'federal',
                'sphere'             => 'federal',
                'validity_days'      => 30,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => 'https://transfere.gov.br',
                'instructions'       => "## Como obter\n\nConsulta no **Transferegov** (antigo SICONV/SIAFI).\n\n**Passos:**\n1. Acesse: https://transfere.gov.br\n2. Consulte a situação da entidade no CAUC (Caderno de Exigências para Transferência).\n3. O sistema exibe pendências em tempo real.\n\n> Exigido apenas para convênios com o governo federal. Regularize pendências no CAUC antes de candidatar a editais federais.",
                'sort_order'         => 250,
            ],

            // =========================================================
            // 3. CERTIDÕES ESTADUAIS (PE)
            // =========================================================
            [
                'name'               => 'Certidão de Regularidade Fiscal — Sefaz-PE',
                'category'           => 'estadual',
                'sphere'             => 'estadual',
                'validity_days'      => 60,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => true,
                'official_url'       => 'https://www.sefaz.pe.gov.br/certidoes',
                'instructions'       => "## Como obter\n\nEmissão **gratuita e online** pela Secretaria da Fazenda de Pernambuco.\n\n**Passos:**\n1. Acesse: https://www.sefaz.pe.gov.br/certidoes\n2. Informe o CNPJ.\n3. Emita e salve o PDF.\n\n**Validade:** 60 dias.\n\n> Em caso de débitos estaduais, contate a Sefaz-PE para parcelamento ou regularização.",
                'sort_order'         => 300,
            ],
            [
                'name'               => 'Certidão Negativa da Dívida Ativa Estadual — PGE-PE',
                'category'           => 'estadual',
                'sphere'             => 'estadual',
                'validity_days'      => 60,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => true,
                'official_url'       => 'https://www.pge.pe.gov.br',
                'instructions'       => "## Como obter\n\nEmissão online pela **Procuradoria Geral do Estado de Pernambuco (PGE-PE)**.\n\n**Passos:**\n1. Acesse: https://www.pge.pe.gov.br\n2. Localize o serviço de certidões.\n3. Informe o CNPJ e emita.\n\n**Validade:** 60 dias.",
                'sort_order'         => 310,
            ],
            [
                'name'               => 'Certidão de Distribuição Cível e Criminal — TJPE',
                'category'           => 'estadual',
                'sphere'             => 'estadual',
                'validity_days'      => 90,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => 'https://www.tjpe.jus.br/certidoes',
                'instructions'       => "## Como obter\n\nEmissão pelo **Tribunal de Justiça de Pernambuco (TJPE)**.\n\n**Passos:**\n1. Acesse: https://www.tjpe.jus.br/certidoes\n2. Solicite certidão de distribuição de ações cíveis e criminais.\n3. Informe o CNPJ da entidade.\n4. Salve o PDF.\n\n**Validade:** 90 dias (verificar o edital).",
                'sort_order'         => 320,
            ],
            [
                'name'               => 'Antecedentes Criminais — Polícia Civil de PE (voluntários)',
                'category'           => 'estadual',
                'sphere'             => 'estadual',
                'validity_days'      => 180,
                'requires_history'   => false,
                'is_per_person'      => true,
                'is_public_by_default' => false,
                'official_url'       => 'https://www.sds.pe.gov.br',
                'instructions'       => "## Como obter\n\nEmissão pela **Secretaria de Defesa Social de Pernambuco (SDS-PE)**.\n\n**Passos:**\n1. Acesse: https://www.sds.pe.gov.br\n2. Localize o serviço de antecedentes criminais.\n3. Faça o agendamento ou emita online com CPF do solicitante.\n4. Validade: 180 dias (exigido especialmente para quem trabalha com crianças e adolescentes).\n\n> Obrigatório pelo **ECA** para voluntários em contato com crianças/adolescentes.",
                'sort_order'         => 330,
            ],

            // =========================================================
            // 4. CERTIDÕES MUNICIPAIS (JABOATÃO DOS GUARARAPES)
            // =========================================================
            [
                'name'               => 'CND Municipal — ISS, IPTU, Dívida Ativa (Prefeitura de Jaboatão)',
                'category'           => 'municipal',
                'sphere'             => 'municipal',
                'validity_days'      => 60,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => true,
                'official_url'       => 'https://www.jaboatao.pe.gov.br',
                'instructions'       => "## Como obter\n\nSolicite na **Secretaria de Finanças da Prefeitura de Jaboatão dos Guararapes**.\n\n**Passos:**\n1. Acesse o portal: https://www.jaboatao.pe.gov.br\n2. Verifique se há serviço online de certidões.\n3. Caso contrário, compareça presencialmente com CNPJ e documentos da entidade.\n\n**Validade:** 60 dias.\n\n> ONGs podem ter isenção de IPTU e ISS. Consulte a secretaria para regularizar antes de solicitar a certidão.",
                'sort_order'         => 400,
            ],
            [
                'name'               => 'Inscrição Municipal (CIM) de Jaboatão',
                'category'           => 'municipal',
                'sphere'             => 'municipal',
                'validity_days'      => null,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => 'https://www.jaboatao.pe.gov.br',
                'instructions'       => "## Como obter\n\nA Inscrição Municipal (CIM) é emitida pela **Prefeitura de Jaboatão dos Guararapes** no ato do cadastro da entidade.\n\n**Passos:**\n1. Acesse: https://www.jaboatao.pe.gov.br\n2. Localize o serviço \"Inscrição Municipal\" ou \"Cadastro de Contribuintes\".\n3. Apresente CNPJ, estatuto e endereço da sede.\n\n> Nem todas as ONGs precisam de CIM. Verifique com a prefeitura se a atividade exige.",
                'sort_order'         => 410,
            ],

            // =========================================================
            // 5. CONTÁBIL / FINANCEIRO
            // =========================================================
            [
                'name'               => 'Balanço Patrimonial (assinado por contador CRC)',
                'category'           => 'contabil',
                'sphere'             => 'interno',
                'validity_days'      => 365,
                'requires_history'   => true,
                'is_per_person'      => false,
                'is_public_by_default' => true,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\nElaborado pelo **contador responsável** (com assinatura e CRC), conforme **ITG 2002 — Entidades sem Finalidade de Lucros**.\n\n**Documentos do conjunto contábil obrigatório (ITG 2002):**\n- Balanço Patrimonial (BP)\n- DRE — Demonstração do Resultado do Exercício\n- DMPL — Demonstração das Mutações do Patrimônio Líquido\n- DFC — Demonstração dos Fluxos de Caixa\n- Notas Explicativas\n\n**Prazo:** elaborar e publicar até **30/04** do ano seguinte ao exercício.\n\n> Guarde todos os anos (histórico exigido por editais e prestações de contas).",
                'sort_order'         => 500,
            ],
            [
                'name'               => 'DRE — Demonstração do Resultado do Exercício',
                'category'           => 'contabil',
                'sphere'             => 'interno',
                'validity_days'      => 365,
                'requires_history'   => true,
                'is_per_person'      => false,
                'is_public_by_default' => true,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\nFaz parte do conjunto contábil obrigatório (ITG 2002). Elaborada pelo contador CRC.\n\n> Sempre junto com o Balanço Patrimonial e demais demonstrações.",
                'sort_order'         => 510,
            ],
            [
                'name'               => 'Balancete de Verificação',
                'category'           => 'contabil',
                'sphere'             => 'interno',
                'validity_days'      => null,
                'requires_history'   => true,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\nElaborado mensalmente ou por período pelo contador. Alguns editais exigem o balancete do exercício mais recente.\n\n> Solicite ao contador responsável pela contabilidade da ONG.",
                'sort_order'         => 520,
            ],
            [
                'name'               => 'DMPL, DFC e Notas Explicativas (ITG 2002)',
                'category'           => 'contabil',
                'sphere'             => 'interno',
                'validity_days'      => 365,
                'requires_history'   => true,
                'is_per_person'      => false,
                'is_public_by_default' => true,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\nDemonstrações complementares exigidas pela **ITG 2002**:\n- **DMPL:** Demonstração das Mutações do Patrimônio Líquido\n- **DFC:** Demonstração dos Fluxos de Caixa\n- **Notas Explicativas:** contexto e metodologias contábeis\n\nElaboradas pelo contador CRC junto com o restante do conjunto contábil anual.",
                'sort_order'         => 530,
            ],
            [
                'name'               => 'Parecer do Conselho Fiscal (anual)',
                'category'           => 'contabil',
                'sphere'             => 'interno',
                'validity_days'      => 365,
                'requires_history'   => true,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\nO Conselho Fiscal da associação emite o parecer após análise das demonstrações contábeis.\n\n**Passos:**\n1. Apresente o conjunto contábil ao Conselho Fiscal.\n2. O Conselho emite parecer aprovando ou indicando ressalvas.\n3. Assinar e arquivar com as demonstrações contábeis do exercício.\n\n> Previsto no estatuto. Se a ONG não tiver Conselho Fiscal formal, constitua-o.",
                'sort_order'         => 540,
            ],
            [
                'name'               => 'Prestação de Contas Anual / Relatório de Atividades',
                'category'           => 'contabil',
                'sphere'             => 'interno',
                'validity_days'      => 365,
                'requires_history'   => true,
                'is_per_person'      => false,
                'is_public_by_default' => true,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\nDocumento elaborado pela diretoria e aprovado em assembleia geral ordinária (AGO).\n\n**Conteúdo mínimo:**\n- Atividades realizadas no período\n- Número de beneficiários atendidos\n- Recursos captados e aplicados\n- Parcerias e convênios vigentes\n- Metas x resultados\n\n**Prazo:** até 30 de abril do ano seguinte.\n\n> Exigido pelo MROSC para renovação de parcerias e registro em conselhos.",
                'sort_order'         => 550,
            ],
            [
                'name'               => 'Plano de Trabalho / Plano de Ação Anual',
                'category'           => 'contabil',
                'sphere'             => 'interno',
                'validity_days'      => 365,
                'requires_history'   => true,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\nElaborado pela diretoria e aprovado em assembleia.\n\n**Conteúdo mínimo:**\n- Objetivos e metas para o período\n- Atividades planejadas\n- Cronograma\n- Recursos previstos\n- Indicadores de acompanhamento\n\n> Essencial para submissão de projetos a editais (MROSC exige plano de trabalho detalhado).",
                'sort_order'         => 560,
            ],

            // =========================================================
            // 6. TITULAÇÕES, REGISTROS E CONSELHOS
            // =========================================================
            [
                'name'               => 'Inscrição no CMAS — Conselho Municipal de Assistência Social de Jaboatão',
                'category'           => 'titulacao',
                'sphere'             => 'municipal',
                'validity_days'      => 365,
                'requires_history'   => true,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => 'https://www.jaboatao.pe.gov.br',
                'instructions'       => "## Como obter\n\nSolicite ao **Conselho Municipal de Assistência Social de Jaboatão dos Guararapes (CMAS)**.\n\n**Requisitos gerais:**\n- Estatuto registrado com finalidade de assistência social\n- Ata de eleição da diretoria vigente\n- Demonstrações contábeis do último exercício\n- Relatório de atividades\n- Comprovante de endereço\n- CNPJ regular\n\n**Renovação:** geralmente anual ou bienal.\n\n> A inscrição no CMAS é pré-requisito para cadastro no CNEAS e acesso a fundos municipais (FMAS).",
                'sort_order'         => 600,
            ],
            [
                'name'               => 'Registro no CMDCA — Conselho Municipal dos Direitos da Criança e do Adolescente',
                'category'           => 'titulacao',
                'sphere'             => 'municipal',
                'validity_days'      => 730,
                'requires_history'   => true,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => 'https://www.jaboatao.pe.gov.br',
                'instructions'       => "## Como obter\n\nSolicite ao **CMDCA de Jaboatão dos Guararapes**.\n\n**Requisitos gerais:**\n- Atuar no atendimento de crianças e adolescentes\n- Estatuto com finalidade compatível\n- Documentação completa da entidade\n- Certidões negativas federais, estaduais e municipais\n- Antecedentes criminais dos dirigentes\n\n**Validade:** tipicamente 2 anos.\n\n> Obrigatório para acesso ao FIA (Fundo para a Infância e Adolescência) e participação em editais do CMDCA.",
                'sort_order'         => 610,
            ],
            [
                'name'               => 'Registro no Conselho Municipal da Mulher',
                'category'           => 'titulacao',
                'sphere'             => 'municipal',
                'validity_days'      => 730,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => false,
                'official_url'       => 'https://www.jaboatao.pe.gov.br',
                'instructions'       => "## Como obter\n\nSolicite ao **Conselho Municipal da Mulher de Jaboatão dos Guararapes** (se houver).\n\n**Requisitos:** documentação institucional completa + comprovação de atuação na área.\n\n> Verifique se o conselho está ativo no município e quais editais exigem este registro.",
                'sort_order'         => 620,
            ],
            [
                'name'               => 'CNEAS — Cadastro Nacional de Entidades de Assistência Social (MDS)',
                'category'           => 'titulacao',
                'sphere'             => 'federal',
                'validity_days'      => 730,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => true,
                'official_url'       => 'https://aplicacoes.mds.gov.br/cneas',
                'instructions'       => "## Como obter\n\nCadastro obrigatório para entidades de assistência social, gerido pelo **Ministério do Desenvolvimento Social (MDS)**.\n\n**Pré-requisito:** Inscrição no CMAS municipal.\n\n**Passos:**\n1. Acesse: https://aplicacoes.mds.gov.br/cneas\n2. Faça login com usuário SUAS Web.\n3. Preencha os dados da entidade e envie a documentação exigida.\n4. Aguarde análise do CMAS e homologação.\n\n> O CNEAS é obrigatório para acesso ao cofinanciamento federal (FNAS) e editais do MDS.",
                'sort_order'         => 630,
            ],
            [
                'name'               => 'Título de Utilidade Pública Municipal',
                'category'           => 'titulacao',
                'sphere'             => 'municipal',
                'validity_days'      => null,
                'requires_history'   => false,
                'is_per_person'      => false,
                'is_public_by_default' => true,
                'official_url'       => 'https://www.jaboatao.pe.gov.br',
                'instructions'       => "## Como obter\n\nSolicite à **Câmara Municipal de Jaboatão dos Guararapes** (processo legislativo).\n\n**Requisitos gerais:**\n- Mínimo de 3 anos de existência comprovada\n- Prestação de serviços relevantes à comunidade local\n- Documentação completa da entidade\n- Sem fins lucrativos comprovado\n\n**Processo:** petição ao vereador ou diretamente à Câmara Municipal.\n\n> O título facilita acesso a editais municipais e pode gerar isenções fiscais.",
                'sort_order'         => 640,
            ],
            [
                'name'               => 'CEBAS — Certificação de Entidades Beneficentes de Assistência Social',
                'category'           => 'titulacao',
                'sphere'             => 'federal',
                'validity_days'      => 1825,
                'requires_history'   => true,
                'is_per_person'      => false,
                'is_public_by_default' => true,
                'official_url'       => 'https://www.gov.br/mds/pt-br/acoes-e-programas/cebas',
                'instructions'       => "## Como obter\n\nCertificação federal concedida pelo **Ministério responsável** conforme a área de atuação (Assistência Social → MDS; Educação → MEC; Saúde → MS).\n\n**Requisitos:**\n- Mínimo 3 anos de existência e funcionamento regular\n- Inscrição no CMAS/CMDCA\n- Prestação gratuita de serviços ao SUS (saúde) ou à rede socioassistencial\n- Demonstrações contábeis dos últimos 3 anos\n\n**Acesso:**\n1. Acesse: https://www.gov.br/mds/pt-br/acoes-e-programas/cebas\n2. Protocole pelo sistema Requerimento CEBAS.\n\n**Validade:** 1 a 5 anos (conforme análise). Renovar com antecedência de 6 meses.\n\n> O CEBAS garante isenção de INSS patronal (cota patronal), COFINS, CSLL e PIS sobre receitas de atividades fins.",
                'sort_order'         => 650,
            ],

            // =========================================================
            // 7. DOCUMENTOS PESSOAIS / VOLUNTÁRIOS
            // =========================================================
            [
                'name'               => 'Termo de Adesão de Voluntariado (Lei 9.608/1998)',
                'category'           => 'pessoal',
                'sphere'             => 'interno',
                'validity_days'      => 365,
                'requires_history'   => false,
                'is_per_person'      => true,
                'is_public_by_default' => false,
                'official_url'       => 'https://www.planalto.gov.br/ccivil_03/leis/L9608.htm',
                'instructions'       => "## Como obter\n\nDocumento elaborado pela própria ONG com base na **Lei 9.608/1998** (Lei do Voluntariado).\n\n**Conteúdo obrigatório:**\n- Identificação da entidade e do voluntário\n- Atividade a ser prestada\n- Condições do serviço voluntário\n- Sem vínculo empregatício\n\n**Modelo:** disponível no planalto: https://www.planalto.gov.br/ccivil_03/leis/L9608.htm\n\n**Validade:** recomenda-se renovar anualmente.\n\n> Sem o termo assinado, o voluntário pode alegar vínculo empregatício.",
                'sort_order'         => 700,
            ],
            [
                'name'               => 'Certidão de Antecedentes Criminais — Voluntários com Crianças (Polícia Civil-PE)',
                'category'           => 'pessoal',
                'sphere'             => 'estadual',
                'validity_days'      => 180,
                'requires_history'   => false,
                'is_per_person'      => true,
                'is_public_by_default' => false,
                'official_url'       => 'https://www.sds.pe.gov.br',
                'instructions'       => "## Como obter\n\nExigida pelo **ECA** para voluntários que atuam diretamente com crianças e adolescentes.\n\n**Passos:**\n1. Acesse: https://www.sds.pe.gov.br (SDS-PE)\n2. Localize o serviço de antecedentes criminais.\n3. O voluntário solicita com seu CPF.\n4. Validade: até 6 meses (verificar exigência do edital/conselho).\n\n> Renove semestralmente para voluntários em contato direto com crianças.",
                'sort_order'         => 710,
            ],
            [
                'name'               => 'RG e CPF de Voluntários e Dirigentes',
                'category'           => 'pessoal',
                'sphere'             => 'interno',
                'validity_days'      => null,
                'requires_history'   => false,
                'is_per_person'      => true,
                'is_public_by_default' => false,
                'official_url'       => null,
                'instructions'       => "## Como obter\n\n**RG:** Secretaria de Defesa Social de PE (SDS-PE): https://www.sds.pe.gov.br\n**CPF:** Receita Federal: https://www.gov.br/receitafederal/pt-br/assuntos/cadastros/cpf\n\n> Solicite cópia autenticada ou apresente o original para autenticação. Armazene com segurança.",
                'sort_order'         => 720,
            ],
        ];

        foreach ($types as $i => $type) {
            DocumentType::firstOrCreate(
                [
                    'institution_id' => $id,
                    'name'           => $type['name'],
                ],
                array_merge($type, ['institution_id' => $id])
            );
        }
    }
}
